### ISSUE TITLE
change of header names in exchange data

### ISSUE THREAD

**Issue by tokami** [casperwberg/surveyIndex#1]
Unfortunately, some column names of the Exchange data file have changed impeding the execution of some functions. I found following functions referring to specific column names:

- `fitALK()`
- `fitALKone()`
- `fixAgeGroup()`

The name of 2 required columns changed in the Exchange data:

`Age` changed to `AgeRings`
`NoAtALK` changed to `CANoAtLngt`

This influences also the example in `getSurveyIdx`

**Comment by casperwberg** [comment]
This issue should be resolved by installing the latest version of the DATRAS package.

Now, when data are parsed from the exchange format, the new column names are - if present - renamed to the old names.
